const fs = require('fs');

// 1. Update index.html
let html = fs.readFileSync('frontend/index.html', 'utf8');

const tabButtons = `
            <button class="tab-btn" data-tab="ast"  onclick="switchTab('ast')">
              <span class="dot"></span>AST
            </button>
            <button class="tab-btn" data-tab="tokens"  onclick="switchTab('tokens')">
              <span class="dot"></span>Tokens
            </button>
            <button class="tab-btn" data-tab="optTac"  onclick="switchTab('optTac')">
              <span class="dot"></span>Optimized TAC
            </button>
            <button class="tab-btn" data-tab="asm"  onclick="switchTab('asm')">
              <span class="dot"></span>Assembly Code
            </button>
`;
html = html.replace(/<button class="tab-btn" data-tab="ast".*?<\/button>\s*/s, tabButtons);

const newPanels = `
        </div>

        <!-- Tokens Panel -->
        <div class="tab-panel" id="panel-tokens">
          <div class="ir-description" style="border-color:#3b82f6;">
            <strong>Lexical Analysis (Tokens)</strong> — The sequence of tokens generated by the lexer from the input expression.
          </div>
          <div class="table-wrap" id="tokensTableWrap">
            <div class="empty-state"><div class="icon">🏷️</div><p>Enter an expression and click <strong>Compile</strong></p></div>
          </div>
        </div>

        <!-- Optimized TAC Panel -->
        <div class="tab-panel" id="panel-optTac">
          <div class="ir-description" style="border-color:#eab308;">
            <strong>Code Optimization (Optimized TAC)</strong> — TAC after applying Constant Folding and Copy Propagation.
          </div>
          <div id="optTacOutput">
            <div class="empty-state"><div class="icon">✨</div><p>Enter an expression and click <strong>Compile</strong></p></div>
          </div>
          <div class="table-wrap" id="optTacTableWrap" style="display:none; margin-top:16px"></div>
        </div>

        <!-- Assembly Code Panel -->
        <div class="tab-panel" id="panel-asm">
          <div class="ir-description" style="border-color:#ef4444;">
            <strong>Code Generation (Assembly)</strong> — Target x86-like assembly code generated from the intermediate representation.
          </div>
          <div class="table-wrap" style="background:#111116; border:1px solid rgba(255,255,255,0.1); border-radius:8px; padding:16px; font-family:var(--font-mono, monospace); font-size:14px; white-space:pre; overflow-x:auto; color: #e2e8f0;" id="asmOutput">
            <div class="empty-state"><div class="icon">⚙️</div><p>Enter an expression and click <strong>Compile</strong></p></div>
          </div>
        </div>
`;
html = html.replace(/<\/div>\s*<\/div><!-- \/resultCard -->/s, newPanels + "\n      </div><!-- /resultCard -->");

fs.writeFileSync('frontend/index.html', html);
console.log('Successfully updated frontend/index.html');

// 2. Update app.js
let appJs = fs.readFileSync('frontend/app.js', 'utf8');

// Update renderResults
appJs = appJs.replace(
  /if \(data\.ast\) renderAST\(data\.ast\);/g,
  "if (data.ast) renderAST(data.ast);\n  if (data.tokens) renderTokens(data.tokens);\n  if (data.optimizedTac) renderOptimizedTAC(data.optimizedTac);\n  if (data.assembly) renderAssembly(data.assembly);"
);

// Append rendering functions at the bottom
const renderFuncs = `

// ─── Tokens ───────────────────────────────────────────────────
function renderTokens(tokens) {
  document.getElementById('tokensTableWrap').innerHTML = buildTable(
    ['#', 'Type', 'Value'],
    tokens.map((r, i) => [
      '<span class="step-badge">' + i + '</span>',
      '<span class="op-chip" style="background:rgba(59,130,246,0.2);color:#60a5fa;">' + r.type + '</span>',
      escHtml(r.value),
    ]),
    i => i * 10
  );
}

// ─── Optimized TAC ────────────────────────────────────────────
function renderOptimizedTAC(tac) {
  const out = document.getElementById('optTacOutput');
  const tableWrap = document.getElementById('optTacTableWrap');

  out.innerHTML = '<div class="tac-mono">' +
    tac.map((instr, i) => {
      const delay = i * 60;
      const tacStr = instr.tacString || '';

      const controlOps = ['LABEL', 'GOTO', 'ifFalse', 'param', 'return', 'call'];
      if (controlOps.includes(instr.operator)) {
        const isLabel  = instr.operator === 'LABEL';
        const isJump   = instr.operator === 'GOTO' || instr.operator === 'ifFalse';
        const color    = isLabel ? '#f59e0b' : isJump ? '#a78bfa' : '#67e8f9';
        return '<div class="tac-line" style="animation-delay:' + delay + 'ms">' +
          '<span class="ln">' + String(i).padStart(2,'0') + ':</span><span style="color:' + color + '; font-weight:600;">' + escHtml(tacStr) + '</span>' +
        '</div>';
      }

      const lhs = '<span class="res">' + escHtml(String(instr.result ?? '')) + '</span>';
      const eql = '<span class="eql">=</span>';
      let rhs = '';
      if (instr.op2 && instr.op2 !== '-') {
        rhs = '<span class="operand">' + escHtml(String(instr.op1 ?? '')) + '</span><span class="opr">' + escHtml(instr.operator) + '</span><span class="operand">' + escHtml(String(instr.op2)) + '</span>';
      } else if (instr.operator === '=') {
        rhs = '<span class="operand">' + escHtml(String(instr.op1 ?? '')) + '</span>';
      } else {
        rhs = '<span class="opr">' + escHtml(instr.operator) + '</span> <span class="operand">' + escHtml(String(instr.op1 ?? '')) + '</span>';
      }
      return '<div class="tac-line" style="animation-delay:' + delay + 'ms">' +
        '<span class="ln">' + String(i).padStart(2,'0') + ':</span>' + lhs + ' ' + eql + ' ' + rhs +
      '</div>';
    }).join('') + '</div>';

  tableWrap.style.display = 'block';
  tableWrap.innerHTML = buildTable(
    ['#', 'Result', 'Operand 1', 'Operator', 'Operand 2'],
    tac.map((r, i) => [
      '<span class="step-badge">' + r.step + '</span>',
      '<span class="result-cell">' + r.result + '</span>',
      r.op1,
      '<span class="op-chip" style="background:rgba(234,179,8,0.2);color:#facc15;">' + r.operator + '</span>',
      r.op2 || '—',
    ]),
    i => i * 60
  );
}

// ─── Assembly ─────────────────────────────────────────────────
function renderAssembly(asm) {
  const out = document.getElementById('asmOutput');
  out.innerHTML = asm.map((line, i) => {
    let color = '#e2e8f0';
    if (line.trim().startsWith(';')) color = '#64748b'; // comment
    else if (line.trim().endsWith(':')) color = '#f59e0b'; // label
    else if (line.trim().startsWith('MOV')) color = '#38bdf8';
    else if (['ADD', 'SUB', 'IMUL', 'IDIV'].some(op => line.trim().startsWith(op))) color = '#4ade80';
    else if (['JMP', 'JE', 'JNE'].some(op => line.trim().startsWith(op))) color = '#a78bfa';
    return '<div style="color:' + color + ';">' + escHtml(line) + '</div>';
  }).join('');
}
`;

// Only append if it's not already there
if (!appJs.includes('function renderTokens')) {
  // Append before Mode Switcher or at the end
  appJs = appJs.replace('// ─── Mode Switcher', renderFuncs + '\n// ─── Mode Switcher');
}

// Add export mapping for tokens and optTac
appJs = appJs.replace(
  /\} else if \(tab === 'ast'\) \{/g,
  `} else if (tab === 'tokens') {
    title = 'Lexical Tokens';
    headers = ['Index', 'Type', 'Value'];
    rows = currentData.tokens.map((r, i) => [i, r.type, r.value]);
  } else if (tab === 'optTac') {
    title = 'Optimized Three Address Code';
    headers = ['Step', 'Result', 'Operand 1', 'Operator', 'Operand 2'];
    rows = currentData.optimizedTac.map(r => [r.step, r.result, r.op1, r.operator, r.op2]);
  } else if (tab === 'ast') {`
);

fs.writeFileSync('frontend/app.js', appJs);
console.log('Successfully updated frontend/app.js');
